TOPDIR = ..\..\..

SUBDIRS =

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

INCLUDE_CXXFLAGS = \
	/D_WIN32_WINNT=0x504

INCLUDE_DIRS = \
	/I. \
	/I$(TOPDIR) \
	/I$(TOPDIR)\src \
	/I$(TOPDIR)\src\wolfilter \
	/I$(TOPDIR)\include \
	/I$(TOPDIR)\3rdParty\gtest\include \
	/I$(TOPDIR)\wtest\include
	/I"$(BOOST_INCLUDE_DIR)"

INCLUDE_LDFLAGS = \
	$(BOOST_LDFLAGS)

INCLUDE_LIBS = \
	$(TOPDIR)\src\libconfig\wfconfig.lib \
	$(TOPDIR)\src\libprovider\wfprovider.lib \
	$(TOPDIR)\src\libwolframe\wolframe.lib \
	$(TOPDIR)\src\libwolframe_serialize\wolframe_serialize.lib \
	$(TOPDIR)\src\libwolframe_database\wolframe_database.lib \
	$(TOPDIR)\src\libwolframe_langbind\wolframe_langbind.lib \
	$(TOPDIR)\src\libwfsingleton\wfsingleton.lib \
	$(TOPDIR)\3rdParty\gtest\gtest-all.obj \
	$(TOPDIR)\wtest\wtest.lib \
	advapi32.lib \

# Postgresql
!IFDEF WITH_PGSQL

INCLUDE_LIBS = \
	$(INCLUDE_LIBS) "$(PGSQL_DIR)\lib\libpq.lib"

!ENDIF

# Oracle
!IFDEF WITH_ORACLE

INCLUDE_LIBS = \
	$(INCLUDE_LIBS) "$(ORACLE_DIR)\sdk\lib\msvc\oci.lib"
!ENDIF


CPP_OBJS = \
	testWolfilterFiles.obj

CPP_BINS = \
	testWolfilter.exe

all: $(CPP_OBJS) $(CPP_BINS)

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

modules: libwolframe
testWolfilter.exe: testWolfilter.obj $(CPP_OBJS) $(TOPDIR)\src\libwfsingleton\logger\wolframemsg.res

local_clean:
	@-erase $(CPP_BINS) 2>NUL
	@-erase $(CPP_OBJS) 2>NUL

local_distclean:

local_test:
	@-copy $(TOPDIR)\src\libwfsingleton\wfsingleton.dll . >NUL
	@-if not exist temp mkdir temp 
	@-erase /q temp 2>NUL
	!IFDEF WITH_LIBXML2
	@-copy "$(ZLIB_DIR)\bin\zlib1.dll" . >NUL
	@-copy "$(ICONV_DIR)\bin\iconv.dll" . >NUL
	@-copy "$(LIBXML2_DIR)\bin\libxml2.dll" . >NUL
	!ENDIF
	!IFDEF WITH_LIBXSLT
	@-copy "$(LIBXSLT_DIR)\bin\libxslt.dll" . >NUL 
	!ENDIF
	!IFDEF WITH_SSL
	@-copy "$(OPENSSL_DIR)\bin\libeay32.dll" . >NUL 
	@-copy "$(OPENSSL_DIR)\bin\ssleay32.dll" . >NUL 
	!ENDIF
	!IFDEF WITH_PGSQL
	@-copy "$(PGSQL_DIR)\lib\libpq.dll" . >NUL 
	!IFDEF PGDLL_WITH_I18N
	@-copy "$(PGSQL_DIR)\bin\libintl*.dll" . >NUL 
	@-copy "$(PGSQL_DIR)\bin\libiconv*.dll" . >NUL 
	!ENDIF
	!ENDIF
	!IFDEF WITH_ORACLE
	@-copy "$(ORACLE_DIR)\*.dll" . >NUL 
	!ENDIF
	@-.\testWolfilter 


