TOPDIR = ..

SUBDIRS = \
	libwolframe \
	libwfsingleton \
	libwolframe_serialize \
	libwolframe_database \
	libwolframe_langbind \
	libconfig \
	libprovider \
	modules \
	wolframed \
	wolfilter \
	wolfwizard

!INCLUDE $(TOPDIR)\makefiles\nmake\platform.mk

!INCLUDE $(TOPDIR)\makefiles\nmake\sub.mk

local_all:

local_clean:

local_distclean:

local_test:

